version: "3.3"

services:

  influxdb:
    container_name: influxdb
    environment:
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      # - INFLUXDB_ADMIN_USER=admin
      # - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_HTTP_LOG_ENABLED=false
    image: influxdb:1.4.3
    restart: always
    volumes:
      - ./data:/var/lib/influxdb
      - ./practices:/practices
    ports:
      - 8086:8086

  chronograf:
    container_name: chronograf
    image: quay.io/influxdb/chronograf:1.4.1.3
    ports:
      - 8888:8888
